### ISSUE TITLE
classification of synapse distribution

### ISSUE THREAD

**Issue by andyweic** [Upward-Spiral-Science/chengchang#3]
Hi Dr. Vogelstein, 
We are having trouble framing our project into a classification (or regression) question. Our data is inherently unlabeled, and our general inclination with this project is to sort to data into clusters of various features, but it is not immediately obvious to us how this fits in a classification mindset.  

Or best idea at the moment is to attempt to first separate the synapses by the Z-layers. In the exploratory phase, we noticed that each Z-layer seemed to have a density of synapses distinct from the adjacent layers. So we could define classes based on the Z-layer. Then we can transform the synapse count dataset into a new dataset and attempt to classify this transformed set. An example transformation could be the mean density of kernels of voxels across each X-Y plane (an example kernel could be an nxn voxel grid, again, in the X-Y dimensions). 

Not sure if that was clear, but basically, this is our best idea at the moment. It involves arbitrarily defining different classes within our domain: by Z-value.  We were hoping to get your thoughts/suggestions on this idea.

Thanks!

@kchang17 @trileica @gkiar

**Comment by jovo** [comment]
Cool! Swing by thurs before class?
Briefly, can you predict z from xy?

On Wednesday, February 24, 2016, andyweic notifications@github.com wrote:

> Hi Dr. Vogelstein,
> We are having trouble framing our project into a classification (or
> regression) question. Our data is inherently unlabeled, and our general
> inclination with this project is to sort to data into clusters of various
> features, but it is not immediately obvious to us how this fits in a
> classification mindset.
> 
> Or best idea at the moment is to attempt to first separate the synapses by
> the Z-layers. In the exploratory phase, we noticed that each Z-layer seemed
> to have a density of synapses distinct from the adjacent layers. So we
> could define classes based on the Z-layer. Then we can transform the
> synapse count dataset into a new dataset and attempt to classify this
> transformed set. An example transformation could be the mean density of
> kernels of voxels across each X-Y plane (an example kernel could be an nxn
> voxel grid, again, in the X-Y dimensions).
> 
> Not sure if that was clear, but basically, this is our best idea at the
> moment. It involves arbitrarily defining different classes within our
> domain: by Z-value. We were hoping to get your thoughts/suggestions on this
> idea.
> 
> Thanks!
> 
> @kchang17 https://github.com/kchang17 @trileica
> https://github.com/trileica @gkiar https://github.com/gkiar
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/chengchang/issues/3.

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by andyweic** [comment]
Yes haha, predict z from xy.

For thurs, I assume you mean swing by your office?

**Comment by jovo** [comment]
yup

On Wed, Feb 24, 2016 at 10:05 AM, andyweic notifications@github.com wrote:

> Yes haha, predict z from xy.
> 
> For thurs, I assume you mean swing by your office?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/chengchang/issues/3#issuecomment-188294916
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by andyweic** [comment]
Are you free in the morning? like around 11? Turns out I have a meeting before class...

**Comment by trileica** [comment]
My class ends at 11:45, and the next one will be the data science.
So if you are busy then I can go to see Dr. Vogelstein.

Wrong reply, please ignore me...

2016-02-24 19:10 GMT-05:00, andyweic notifications@github.com:

> Are you free in the morning? like around 11? Turns out I have a meeting
> before class...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/Upward-Spiral-Science/chengchang/issues/3#issuecomment-188528737

## 

Best Regards,
吳三和 (San-he Wu)

**Comment by andyweic** [comment]
hmmm that might work. Maybe after your class, grab lunch and we can both see Dr. Vogelstein at 12:30 (if that works for him of course)? That way I can my meeting in lab at 1:30. If that time doesn't work, then depending on Dr. Vogelstein's schedule, one of us will meet him.

**Comment by trileica** [comment]
Okay, it sounds great.

**Comment by jovo** [comment]
hi guys - i have office hours 2-3 on TT,
tomorrow i should be around my office 1-3.

On Wed, Feb 24, 2016 at 10:54 PM, San-he Wu notifications@github.com
wrote:

> Okay, it sounds great.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/chengchang/issues/3#issuecomment-188595169
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by andyweic** [comment]
ok great!  San-He I'll be there at 1, but I definitely can't stay too long. Can you be there as well?

**Comment by trileica** [comment]
No problem.
